### ISSUE TITLE
Error when running main.py task 2

### ISSUE THREAD

**Issue by AndreasEike** [Sjyhne/MapAI-Competition#17]
Hello, I am getting an error when running main.py with the following command:

"python main.py --device=cuda --task=2 --submission='submission/' --data-type=validation"

The error is:
Traceback (most recent call last):
  File "C:\Users\<user>\MapAI-Competition-Private\team_template\src\main.py", line 31, in <module>
    evaluate_model_2(args=args)
  File "C:\Users\<user>\MapAI-Competition-Private\team_template\src\model_task_2.py", line 107, in main
    biou_score = biou(label, prediction)
  File "C:\Users\<user>\MapAI-Competition-Private\venv\lib\site-packages\competition_toolkit\eval_functions.py", line 76, in biou
    gt_boundary = _mask_to_boundary(target.astype(np.uint8), dilation_ratio)
  File "C:\Users\<user>\MapAI-Competition-Private\venv\lib\site-packages\competition_toolkit\eval_functions.py", line 43, in _mask_to_boundary
    h, w = mask.shape
ValueError: too many values to unpack (expected 2)

The shape of mask is [4,500,500], and changes based on the batch size and image size. I am using the model as provided in the example in "model_task_2.py", should not this work "out-of-the-box"?

**Comment by Sjyhne** [comment]
Hello!

The main reason for this issue is that I've not considered batching in the code for inference of the validation data for task 1 and task 2. If you choose a batch size of 1 in the data.yaml file for task 1 and task 2 and validation, then you will not encounter this issue.

**Comment by AndreasEike** [comment]
Okay, that makes sense. It works if i set batch size for "task 2" in data.yaml to 1. Thanks!
